[project]
name = "hermes-ble-nodes"
dynamic = ["version"]
description = "A Hermes BLE node library"
authors = [{ name = "floris vernieuwe", email = "floris@vernieuwe.eu" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=0.22.3",
    "node-hermes-core",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E402"]

[tool.ruff]
line-length = 120
exclude = ["**.pyi", "**/.venv/**", "**/ui"]
include = ["src/**.py", "test/**.py"]

[tool.pyright]
ignore = ["**.pyi", "**/.venv/**", "**/ui"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0"

[tool.pyright.defineConstant]
PYQT5 = false
PYSIDE2 = false
PYQT6 = false
PYSIDE6 = true
